2020-12-10 00:21:21.300 [error] <0.2272.0> CRASH REPORT Process <0.2272.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => get,kind => nil,module => 'Elixir.Access'},[{'Elixir.Access',get,[{ok,#{<<"invoice">> => nil}},<<"invoice">>,nil],[{file,"lib/access.ex"},{line,265}]},{'Elixir.GuardianWeb.Admin.InvoicesController',index,3,[{file,"lib/guardian_web/controllers/admin/invoices_controller.ex"},{line,24}]},{'Elixir.GuardianWeb.Admin.InvoicesController',action,2,[{file,"lib/guardian_web/..."},...]},...]},...},...},...}
2020-12-10 00:21:21.301 [error] <0.2272.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.2271.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => get,kind => nil,module => 'Elixir.Access'},[{'Elixir.Access',get,[{ok,#{<<"invoice">> => nil}},<<"invoice">>,nil],[{file,"lib/access.ex"},{line,265}]},{'Elixir.GuardianWeb.Admin.InvoicesController',index,3,[{file,"lib/guardian_web/controllers/admin/invoices_controller.ex"},{line,24}]},{'Elixir.GuardianWeb.Admin.InvoicesController',action,2,[{file,"lib/guardian_web/co..."},...]},...]},...},...}
2020-12-10 00:22:49.872 [error] <0.2286.0> CRASH REPORT Process <0.2286.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => get,kind => nil,module => 'Elixir.Access'},[{'Elixir.Access',get,[{ok,#{<<"invoice">> => nil}},<<"invoice">>,nil],[{file,"lib/access.ex"},{line,265}]},{'Elixir.GuardianWeb.Admin.InvoicesController',index,3,[{file,"lib/guardian_web/controllers/admin/invoices_controller.ex"},{line,25}]},{'Elixir.GuardianWeb.Admin.InvoicesController',action,2,[{file,"lib/guardian_web/..."},...]},...]},...},...},...}
2020-12-10 00:22:49.873 [error] <0.2286.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.2284.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 3,clauses => nil,function => get,kind => nil,module => 'Elixir.Access'},[{'Elixir.Access',get,[{ok,#{<<"invoice">> => nil}},<<"invoice">>,nil],[{file,"lib/access.ex"},{line,265}]},{'Elixir.GuardianWeb.Admin.InvoicesController',index,3,[{file,"lib/guardian_web/controllers/admin/invoices_controller.ex"},{line,25}]},{'Elixir.GuardianWeb.Admin.InvoicesController',action,2,[{file,"lib/guardian_web/co..."},...]},...]},...},...}
2020-12-10 01:05:42.889 [info] <0.43.0> Application lager started on node nonode@nohost
2020-12-10 01:05:42.905 [info] <0.43.0> Application xmerl started on node nonode@nohost
2020-12-10 01:05:42.918 [info] <0.43.0> Application tools started on node nonode@nohost
2020-12-10 01:05:42.922 [info] <0.43.0> Application jsx started on node nonode@nohost
2020-12-10 01:05:42.940 [info] <0.43.0> Application ranch started on node nonode@nohost
2020-12-10 01:05:42.945 [info] <0.43.0> Application recon started on node nonode@nohost
2020-12-10 01:05:43.036 [info] <0.43.0> Application credentials_obfuscation started on node nonode@nohost
2020-12-10 01:05:43.036 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2020-12-10 01:05:43.062 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2020-12-10 01:05:43.062 [info] <0.43.0> Application amqp started on node nonode@nohost
2020-12-10 01:05:43.069 [info] <0.43.0> Application telemetry_metrics started on node nonode@nohost
2020-12-10 01:05:43.088 [info] <0.43.0> Application telemetry_poller started on node nonode@nohost
2020-12-10 01:05:43.097 [info] <0.43.0> Application jason started on node nonode@nohost
2020-12-10 01:05:43.112 [info] <0.43.0> Application html_entities started on node nonode@nohost
2020-12-10 01:05:43.112 [info] <0.43.0> Application floki started on node nonode@nohost
2020-12-10 01:05:43.124 [info] <0.43.0> Application comeonin started on node nonode@nohost
2020-12-10 01:05:43.124 [info] <0.43.0> Application bcrypt_elixir started on node nonode@nohost
2020-12-10 01:05:43.267 [info] <0.43.0> Application jose started on node nonode@nohost
2020-12-10 01:05:43.268 [info] <0.43.0> Application joken started on node nonode@nohost
2020-12-10 01:05:43.272 [info] <0.43.0> Application phoenix_html started on node nonode@nohost
2020-12-10 01:05:43.282 [info] <0.43.0> Application cowlib started on node nonode@nohost
2020-12-10 01:05:43.293 [info] <0.43.0> Application cowboy started on node nonode@nohost
2020-12-10 01:05:43.297 [info] <0.43.0> Application cowboy_telemetry started on node nonode@nohost
2020-12-10 01:05:43.299 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2020-12-10 01:05:43.302 [info] <0.43.0> Application phoenix_live_view started on node nonode@nohost
2020-12-10 01:05:43.305 [info] <0.43.0> Application phoenix_live_dashboard started on node nonode@nohost
2020-12-10 01:05:43.476 [info] <0.43.0> Application tzdata started on node nonode@nohost
2020-12-10 01:05:43.482 [info] <0.43.0> Application combine started on node nonode@nohost
2020-12-10 01:05:43.482 [info] <0.43.0> Application timex started on node nonode@nohost
2020-12-10 01:05:43.486 [info] <0.43.0> Application filtrex started on node nonode@nohost
2020-12-10 01:05:43.494 [info] <0.43.0> Application scrivener started on node nonode@nohost
2020-12-10 01:05:43.494 [info] <0.43.0> Application scrivener_ecto started on node nonode@nohost
2020-12-10 01:05:43.494 [info] <0.43.0> Application torch started on node nonode@nohost
2020-12-10 01:05:43.496 [info] <0.43.0> Application bamboo started on node nonode@nohost
2020-12-10 01:05:43.498 [info] <0.43.0> Application phoenix_ecto started on node nonode@nohost
2020-12-10 01:05:43.542 [info] <0.43.0> Application guardian started on node nonode@nohost
2020-12-10 01:05:43.581 [info] <0.43.0> Application ex_unit started on node nonode@nohost
2020-12-10 01:53:43.688 [error] <0.3841.0> CRASH REPORT Process <0.3841.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => create,message => nil,module => 'Elixir.GuardianWeb.Admin.NotificationConfigController',reason => nil},[{'Elixir.GuardianWeb.Admin.NotificationConfigController',create,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 146,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"text/html,applicati...">>,...},...}},...},...],...},...]},...},...},...}
2020-12-10 01:53:43.708 [error] <0.3841.0> Cowboy stream 7 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.3503.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => create,message => nil,module => 'Elixir.GuardianWeb.Admin.NotificationConfigController',reason => nil},[{'Elixir.GuardianWeb.Admin.NotificationConfigController',create,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 146,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"text/html,application...">>,...},...}},...},...],...},...]},...},...}
2020-12-10 02:02:20.050 [error] <0.4134.0> CRASH REPORT Process <0.4134.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => severity_filter,message => nil,term => #{<<"daily_notification">> => <<"true">>,<<"daily_notification_time">> => <<"11:11">>,<<"immediate_notification">> => <<"true">>,<<"severity">> => <<"3">>}},[{'Elixir.GuardianWeb.Admin.NotificationConfigController',reportUserConfiguration,2,[{file,"lib/guardian_web/controllers/admin/notification_config_controller.ex"},{line,35}]},{'Elixir.GuardianWeb.Admin.NotificationConfigController',...},...]},...},...},...}
2020-12-10 02:02:20.058 [error] <0.4134.0> Cowboy stream 5 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.3963.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => severity_filter,message => nil,term => #{<<"daily_notification">> => <<"true">>,<<"daily_notification_time">> => <<"11:11">>,<<"immediate_notification">> => <<"true">>,<<"severity">> => <<"3">>}},[{'Elixir.GuardianWeb.Admin.NotificationConfigController',reportUserConfiguration,2,[{file,"lib/guardian_web/controllers/admin/notification_config_controller.ex"},{line,35}]},{'Elixir.GuardianWeb.Admin.NotificationConfigController',...},...]},...},...}
2020-12-10 02:02:47.547 [error] <0.4143.0> CRASH REPORT Process <0.4143.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => severity_filter,message => nil,term => #{<<"daily_notification">> => <<"true">>,<<"daily_notification_time">> => <<"11:11">>,<<"immediate_notification">> => <<"true">>,<<"severity">> => <<"3">>}},[{'Elixir.GuardianWeb.Admin.NotificationConfigController',reportUserConfiguration,2,[{file,"lib/guardian_web/controllers/admin/notification_config_controller.ex"},{line,35}]},{'Elixir.GuardianWeb.Admin.NotificationConfigController',...},...]},...},...},...}
2020-12-10 02:02:47.549 [error] <0.4143.0> Cowboy stream 7 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.3963.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => severity_filter,message => nil,term => #{<<"daily_notification">> => <<"true">>,<<"daily_notification_time">> => <<"11:11">>,<<"immediate_notification">> => <<"true">>,<<"severity">> => <<"3">>}},[{'Elixir.GuardianWeb.Admin.NotificationConfigController',reportUserConfiguration,2,[{file,"lib/guardian_web/controllers/admin/notification_config_controller.ex"},{line,35}]},{'Elixir.GuardianWeb.Admin.NotificationConfigController',...},...]},...},...}
2020-12-10 02:02:58.127 [error] <0.4188.0> CRASH REPORT Process <0.4188.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => severity_filter,message => nil,term => #{<<"daily_notification">> => <<"true">>,<<"daily_notification_time">> => <<"11:11">>,<<"immediate_notification">> => <<"true">>,<<"severity_filter">> => <<"1">>}},[{'Elixir.GuardianWeb.Admin.NotificationConfigController',reportUserConfiguration,2,[{file,"lib/guardian_web/controllers/admin/notification_config_controller.ex"},{line,35}]},{'Elixir.GuardianWeb.Admin.NotificationConfigController',...},...]},...},...},...}
2020-12-10 02:02:58.128 [error] <0.4188.0> Cowboy stream 7 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.4145.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => severity_filter,message => nil,term => #{<<"daily_notification">> => <<"true">>,<<"daily_notification_time">> => <<"11:11">>,<<"immediate_notification">> => <<"true">>,<<"severity_filter">> => <<"1">>}},[{'Elixir.GuardianWeb.Admin.NotificationConfigController',reportUserConfiguration,2,[{file,"lib/guardian_web/controllers/admin/notification_config_controller.ex"},{line,35}]},{'Elixir.GuardianWeb.Admin.NotificationConfigController',...},...]},...},...}
2020-12-10 02:15:43.862 [error] <0.4477.0> CRASH REPORT Process <0.4477.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => get_invoices,message => nil,module => 'Elixir.Guardian.NotificationConfigAdmin',reason => nil},[{'Elixir.Guardian.NotificationConfigAdmin',get_invoices,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Guardian.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Guardian.Accounts.User',confirmed_at => #{...},...}],...},...]},...},...},...}
2020-12-10 02:15:43.862 [error] <0.4477.0> Cowboy stream 6 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.4295.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => get_invoices,message => nil,module => 'Elixir.Guardian.NotificationConfigAdmin',reason => nil},[{'Elixir.Guardian.NotificationConfigAdmin',get_invoices,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Guardian.Accounts.User',source => <<"users">>,state => loaded},'__struct__' => 'Elixir.Guardian.Accounts.User',confirmed_at => #{...},...}],...},...]},...},...}
2020-12-10 02:16:20.421 [error] <0.4568.0> CRASH REPORT Process <0.4568.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>NotFoundError: Not Found<br> &nbsp; &nbsp;at /Users/juanvico/Documents/Projects/facultad/asp/guardian/billing/app.js:33:8<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/juanvico/Documents/Projects/facultad/asp/guardian/billing/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;...">>,...},...},...},...},...}
2020-12-10 02:16:20.422 [error] <0.4568.0> Cowboy stream 9 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.4296.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Jason.DecodeError',data => <<"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>NotFoundError: Not Found<br> &nbsp; &nbsp;at /Users/juanvico/Documents/Projects/facultad/asp/guardian/billing/app.js:33:8<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/juanvico/Documents/Projects/facultad/asp/guardian/billing/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at...">>,...},...},...},...}
2020-12-10 02:24:37.091 [error] <0.4780.0> CRASH REPORT Process <0.4780.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => fetch,message => nil,module => 'Elixir.HTTPoison.Response',reason => <<"HTTPoison.Response does not implement the Access behaviour">>},[{'Elixir.HTTPoison.Response',fetch,[#{'__struct__' => 'Elixir.HTTPoison.Response',body => <<"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>NotFoundError: Not Found<br> &nbsp; &nbsp;at /Users/juanvi...">>,...},...],...},...]},...},...},...}
2020-12-10 02:24:37.093 [error] <0.4780.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.4778.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => fetch,message => nil,module => 'Elixir.HTTPoison.Response',reason => <<"HTTPoison.Response does not implement the Access behaviour">>},[{'Elixir.HTTPoison.Response',fetch,[#{'__struct__' => 'Elixir.HTTPoison.Response',body => <<"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>NotFoundError: Not Found<br> &nbsp; &nbsp;at /Users/juanvico...">>,...},...],...},...]},...},...}
2020-12-10 02:36:48.400 [error] <0.5091.0> CRASH REPORT Process <0.5091.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @error not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:config, :conn, :current_user, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,134}]},...]},...},...},...}
2020-12-10 02:36:48.406 [error] <0.5091.0> Cowboy stream 1 with ranch listener 'Elixir.GuardianWeb.Endpoint.HTTP' and connection process <0.5090.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"assign @error not available in eex template.\n\nPlease make sure all proper assigns have been set. If this\nis a child template, ensure assigns are given explicitly by\nthe parent template as they are not automatically forwarded.\n\nAvailable assigns: [:config, :conn, :current_user, :view_module, :view_template]\n">>},[{'Elixir.Phoenix.HTML.Engine','fetch_assign!',2,[{file,"lib/phoenix_html/engine.ex"},{line,134}]},...]},...},...}
